name: Docker Image CI

on:
  push:
    branches: [ "main","develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      # --- Docker Build & Push ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/reembolsofrontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/reembolsofrontend:${{ github.run_number }}

      - name: Deploy to Production
        run: |
          echo "Deploying container to production environment..."
          # Exemplo: docker service update ou kubectl set image
          # docker service update --image ${{ secrets.DOCKERHUB_USERNAME }}/reembolsofrontend:latest reembolsofrontend
